# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: loansdb-deployment
serviceName: loansdb
appLabel: loansdb
appName: loansdb

replicaCount: 1

image:
  repository: mysql
  tag: latest

containerPort: 3306

service:
  type: ClusterIP
  port: 3308
  targetPort: 3306

database:
  accounts_db_enabled: false
  cards_db_enabled: false
  loans_db_enabled: true
  credentials_enabled: true

appname_enabled: true
profile_enabled: true
accounts_db_enabled: false
cards_db_enabled: false
loans_db_enabled: false
config_enabled: false
eureka_enabled: false
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: false