# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: cards-deployment
serviceName: cards
appLabel: cards
appName: cards

replicaCount: 1

image:
  repository: imritam97/cards
  tag: s14

containerPort: 9000

service:
  type: ClusterIP
  port: 9000
  targetPort: 9000

database:
  accounts_db_enabled: false
  cards_db_enabled: false
  loans_db_enabled: false
  credentials_enabled: false

appname_enabled: true
profile_enabled: true
accounts_db_enabled: false
cards_db_enabled: true
loans_db_enabled: false
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false