# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: accounts-deployment
serviceName: accounts
appLabel: accounts
appName: accounts

replicaCount: 1

image:
  repository: imritam97/accounts
  tag: s14

containerPort: 8080

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

database:
  accounts_db_enabled: false
  cards_db_enabled: false
  loans_db_enabled: false
  credentials_enabled: false

appname_enabled: true
profile_enabled: true
accounts_db_enabled: true
cards_db_enabled: false
loans_db_enabled: false
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: true